name: Build and Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: Cache executable
      id: cache-executable
      uses: actions/cache@v4
      with:
        path: ft_ls
        key: executable-${{ hashFiles('**/*') }}
    - run: make

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - uses: actions/cache@v4
      with:
        path: ft_ls
        key: executable-${{ hashFiles('**/*') }}
    - run: make
    - run: ./test/smoke_test.sh