name: Build and Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: make

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: ./test/smoke_test.sh